-- =========================================================
-- Accounts
-- =========================================================

CREATE TABLE Accounts (
    ACID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ClientID integer NULL,
    LedgerID integer NULL,
    ZID integer NULL,
    WardNo integer NULL,
    PropertyNo integer NULL,
    PartNo integer NULL,
    CitySurveyNo varchar(50) NULL,
    PlotNo varchar(50) NULL,
    O_OnlineNo varchar(50) NULL,
    O_ZID integer NULL,
    O_WardNo integer NULL,
    O_PropertyNo varchar(50) NULL,
    O_PartNo varchar(50) NULL,
    O_CitySurveyNo varchar(50) NULL,
    O_PlotNo varchar(50) NULL,
    O_Usage varchar(50) NULL,
    O_TaxableValue double precision NULL,
    O_AnualRentalValue double precision NULL,
    Aadhar_No varchar(12) NULL,
    "CTID" integer NULL,
    PUID integer NULL,
    O_TotalTax numeric(18,2) NULL,
    Owner_Name varchar(500) NULL,
    Holder_Name varchar(100) NULL,
    Wife_Name varchar(100) NULL,
    BuildingName varchar(50) NULL,
    BuildingNo varchar(50) NULL,
    Address varchar(150) NULL,
    MobileNo varchar(50) NULL,
    Exchange varchar(100) NULL,
    HasToilet boolean NULL,
    ToiletSeats1 smallint NULL,
    ToiletSeats2 smallint NULL,
    HasWaterConnection boolean NULL,
    TotalWaterConnections smallint NULL,
    HasSolarElectricity boolean NULL,
    HasRainWaterHarvesting boolean NULL,
    HasTree boolean NULL,
    Boundry_East varchar(50) NULL,
    Boundry_West varchar(50) NULL,
    Boundry_North varchar(50) NULL,
    Boundry_South varchar(50) NULL,
    LengthOnEast double precision NULL,
    LengthOnWest double precision NULL,
    LengthOnNorth double precision NULL,
    LengthOnSouth double precision NULL,
    Avg_Length double precision NULL,
    Avg_Breadth double precision NULL,
    Area double precision NULL,
    OPA double precision NULL,
    Gharkul boolean DEFAULT false NULL,
    HasGharkul boolean DEFAULT false NULL,
    TreeNos integer DEFAULT 0 NULL,
    HasTenant boolean DEFAULT false NULL,
    HasBore boolean DEFAULT false NULL,
    HasWell boolean DEFAULT false NULL,
    TenantName varchar(100) NULL,
    PhotoPath text NULL,
    MapPath text NULL,
    "Length" double precision DEFAULT 0 NULL,
    Breadth double precision DEFAULT 0 NULL,
    AsmComplete boolean DEFAULT false NOT NULL,
    oldbuiltuparea double precision DEFAULT 0 NULL,
    Remark1 text NULL,
    Remark2 text NULL,
    HasTower boolean DEFAULT false NULL,
    ManualRatableValue boolean DEFAULT false NULL,
    ManualTax boolean DEFAULT false NULL,
    Remarks3 text NULL,
    NumberingRemarks text NULL,
    NumberingDone boolean NULL,
    SurveyDone boolean NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_Accounts PRIMARY KEY (ACID)
);

-- =========================================================
-- AssessedTax
-- =========================================================

CREATE TABLE AssessedTax (
    ACID bigint NULL,
    TaxID integer NULL,
    Amount double precision NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- AssessedTaxCapital
-- =========================================================

CREATE TABLE AssessedTaxCapital (
    ACID bigint NULL,
    TaxID integer NULL,
    Amount double precision NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- AssessedTaxCapitalDetails
-- =========================================================

CREATE TABLE AssessedTaxCapitalDetails (
    ACID bigint NULL,
    PropertyDescription varchar(50) NULL,
    PDID integer NULL,
    TAXID integer NULL,
    AMOUNT integer DEFAULT 0 NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- AssessedTaxRent
-- =========================================================

CREATE TABLE AssessedTaxRent (
    ACID bigint NULL,
    TaxID integer NULL,
    Amount double precision NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- AssessedTaxRentDetails
-- =========================================================

CREATE TABLE AssessedTaxRentDetails (
    ACID bigint NULL,
    PropertyDescription varchar(50) NULL,
    PDID integer NULL,
    TAXID integer NULL,
    AMOUNT integer DEFAULT 0 NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- Assessment
-- =========================================================

CREATE TABLE Assessment (
    ASID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ACID bigint NULL,
    PropertyDescription varchar(50) NULL,
    Floor varchar(10) NULL,
    con_year integer NULL,
    con_type varchar(50) NULL,
    prop_use varchar(50) NULL,
    areaft double precision NULL,
    areamt double precision NULL,
    ratesqmt double precision NULL,
    monthly_rent double precision NULL,
    annual_rent double precision NULL,
    annual_tax_value double precision NULL,
    dep_per double precision NULL,
    dep_amt double precision NULL,
    gap double precision NULL,
    ff double precision NULL,
    weightage double precision NULL,
    taxable_amt double precision NULL,
    zone_point double precision NULL,
    PDID integer NULL,
    "CTID" integer NULL,
    PUID integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_Assessment PRIMARY KEY (ASID)
);

-- =========================================================
-- AssessmentCapital
-- =========================================================

CREATE TABLE AssessmentCapital (
    ACID bigint NULL,
    PropertyDescription varchar(50) NULL,
    floor varchar(10) NULL,
    con_year integer NULL,
    ass_year integer NULL,
    con_type varchar(50) NULL,
    prop_use varchar(50) NULL,
    areaft double precision NULL,
    areamt double precision NULL,
    ratesqmt double precision NULL,
    monthly_rent double precision NULL,
    annual_rent double precision NULL,
    annual_tax_value double precision NULL,
    dep_per double precision NULL,
    dep_amt double precision NULL,
    gap double precision NULL,
    ff double precision NULL,
    weightage double precision NULL,
    taxable_amt double precision NULL,
    zone_point double precision NULL,
    PDID integer NULL,
    "CTID" integer NULL,
    PUID integer NULL,
    rep_per double precision DEFAULT 0 NULL,
    rep_amt integer DEFAULT 0 NULL,
    ManualRatableValue boolean DEFAULT false NULL,
    srnid integer DEFAULT 0 NULL,
    buildingno varchar(10) NULL,
    Holder varchar(50) NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- AssessmentRent
-- =========================================================

CREATE TABLE AssessmentRent (
    ACID bigint NULL,
    PropertyDescription varchar(50) NULL,
    floor varchar(10) NULL,
    con_year integer NULL,
    ass_year integer NULL,
    con_type varchar(50) NULL,
    prop_use varchar(50) NULL,
    areaft double precision NULL,
    areamt double precision NULL,
    ratesqmt double precision NULL,
    monthly_rent double precision NULL,
    annual_rent double precision NULL,
    annual_tax_value double precision NULL,
    dep_per double precision NULL,
    dep_amt double precision NULL,
    gap double precision NULL,
    ff double precision NULL,
    weightage double precision NULL,
    taxable_amt double precision NULL,
    zone_point double precision NULL,
    PDID integer NULL,
    "CTID" integer NULL,
    PUID integer NULL,
    SrNo integer NULL,
    SRNID integer NULL,
    rep_per double precision DEFAULT 0 NULL,
    rep_amt integer DEFAULT 0 NULL,
    ManualRatableValue boolean DEFAULT false NULL,
    buildingno varchar(10) NULL,
    Holder varchar(50) NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- Capital_DepRateOnCT
-- =========================================================

CREATE TABLE Capital_DepRateOnCT (
    DepID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ClientID integer NULL,
    MinYear integer NULL,
    MaxYear integer NULL,
    "CTID" integer NULL,
    ZID integer NULL,
    Per double precision NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_Depreciation PRIMARY KEY (DepID)
);

-- =========================================================
-- CarpetAreas
-- =========================================================

CREATE TABLE CarpetAreas (
    ACID bigint NULL,
    PropID integer NULL,
    CarID integer NULL,
    "Length" double precision NULL,
    Breadth double precision NULL,
    Area double precision NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- Clients
-- =========================================================

CREATE TABLE Clients (
    ClientID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ClientName varchar(255) NULL,
    ClientType varchar(100) NULL,
    TalukaID integer NULL,
    DistID integer NULL,
    StateID integer NULL,
    Pincode char(6) NULL,
    MobileNo varchar(50) NULL,
    PhoneNo varchar(50) NULL,
    Remarks varchar(50) NULL,
    ChangeBuildArea boolean NULL,
    AskBoundry boolean NULL,
    ValuationMethod smallint NULL,
    TaxValueByAmtOrPer boolean NULL,
    Start_year integer NULL,
    End_year integer NULL,
    Sign1Auth varchar(50) NULL,
    Sign2Auth varchar(50) NULL,
    Sign3Auth varchar(50) NULL,
    Sign1 bytea NULL,
    Sign2 bytea NULL,
    Sign3 bytea NULL,
    Logo bytea NULL,
    SeparateWaterTax boolean DEFAULT false NULL,
    TaxOnArea integer DEFAULT 0 NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_Clients PRIMARY KEY (ClientID)
);

-- =========================================================
-- ConstructionTypes
-- =========================================================

CREATE TABLE ConstructionTypes (
    "CTID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ConstructionType varchar(50) NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_ConstructionTypes PRIMARY KEY ("CTID")
);

-- =========================================================
-- DefaultLedgers
-- =========================================================

CREATE TABLE DefaultLedgers (
    DLID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    LedgerIdentity varchar(50) NULL,
    LedgerID integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_DefaultLedgers PRIMARY KEY (DLID)
);

-- =========================================================
-- DemandTemplate
-- =========================================================

CREATE TABLE DemandTemplate (
    TempID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    OrderNo integer DEFAULT 0 NULL,
    TaxID integer DEFAULT 0 NULL,
    LedgerID integer DEFAULT 0 NULL,
    ItemType varchar(50) NULL,
    Heading varchar(50) NULL,
    "Attribute" varchar(50) NULL,
    "Range" varchar(50) NULL,
    Expression varchar(50) NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_DemandTemplate PRIMARY KEY (TempID)
);

-- =========================================================
-- Districts
-- =========================================================

CREATE TABLE Districts (
    DistID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DistrictName varchar(100) NULL,
    StateID integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_Districts PRIMARY KEY (DistID)
);

-- =========================================================
-- EduTaxRates
-- =========================================================

CREATE TABLE EduTaxRates (
    RangeFrom integer NULL,
    RangeTo integer NULL,
    Per1 double precision NULL,
    Per2 double precision NULL,
    TaxID integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- EmpTaxRates
-- =========================================================

CREATE TABLE EmpTaxRates (
    RangeFrom integer NULL,
    RangeTo integer NULL,
    Per double precision NULL,
    TaxID integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- FinancialYears
-- =========================================================

CREATE TABLE FinancialYears (
    FYID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    YearFrom integer NULL,
    YearTo integer NULL,
    Selected boolean NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_FinancialYear PRIMARY KEY (FYID)
);

-- =========================================================
-- FloorFactor
-- =========================================================

CREATE TABLE FloorFactor (
    FLRID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ClientID integer NULL,
    ZID integer NULL,
    Floor varchar(10) NULL,
    Factor double precision NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_FloorFactor PRIMARY KEY (FLRID)
);

-- =========================================================
-- LGIS
-- =========================================================

CREATE TABLE LGIS (
    LGIID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    InstituteTypeName varchar(50) NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_LGIS PRIMARY KEY (LGIID)
);

-- =========================================================
-- LedgerTypes
-- =========================================================

CREATE TABLE LedgerTypes (
    LTID smallint NULL,
    LedgerType varchar(50) NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- Ledgers
-- =========================================================

CREATE TABLE Ledgers (
    LedgerID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    LedgerName text NULL,
    LedgerType smallint NULL,
    ClientID integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_Ledgers PRIMARY KEY (LedgerID)
);

-- =========================================================
-- PhotosMaps
-- =========================================================

CREATE TABLE PhotosMaps (
    ClientID integer NULL,
    ACID bigint NOT NULL,
    Photo bytea NULL,
    "Map" bytea NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- PropertyDesc
-- =========================================================

CREATE TABLE PropertyDesc (
    PDID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PropertyDescription varchar(50) NULL,
    Weightage double precision DEFAULT 0.0 NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_PropertyDesc PRIMARY KEY (PDID)
);

-- =========================================================
-- PropertyUsage
-- =========================================================

CREATE TABLE PropertyUsage (
    PUID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PropertyUse varchar(50) NULL,
    PDID integer NULL,
    TaxAmount integer DEFAULT 0 NULL,
    GWTax integer DEFAULT 0 NULL,
    SWTax integer DEFAULT 0 NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_PropertyHeads PRIMARY KEY (PUID)
);

-- =========================================================
-- PropertyUsageOld
-- =========================================================

CREATE TABLE PropertyUsageOld (
    PUID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PropertyUse varchar(100) NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_PropertyUsageOld PRIMARY KEY (PUID)
);

-- =========================================================
-- RECOUNT
-- =========================================================

CREATE TABLE RECOUNT (
    RID integer NULL,
    RType varchar(50) NULL,
    FYID integer NULL,
    RECNO integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- RateOnCTZonewise_Capital
-- =========================================================

CREATE TABLE RateOnCTZonewise_Capital (
    CTZRID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ClientID integer NULL,
    ZID integer NULL,
    "CTID" integer NULL,
    Rate integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_RateOnCTZonewise PRIMARY KEY (CTZRID)
);

-- =========================================================
-- RateOnCTZonewise_Rent
-- =========================================================

CREATE TABLE RateOnCTZonewise_Rent (
    CTZRID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ClientID integer NULL,
    ZID integer NULL,
    "CTID" integer NULL,
    Rate integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_RateOnCTZonewise_Rent PRIMARY KEY (CTZRID)
);

-- =========================================================
-- ReceiptTemplate
-- =========================================================

CREATE TABLE ReceiptTemplate (
    TempID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    OrderNo integer DEFAULT 0 NULL,
    TaxID integer DEFAULT 0 NULL,
    LedgerID integer DEFAULT 0 NULL,
    ItemType varchar(50) NULL,
    Heading varchar(50) NULL,
    "Attribute" varchar(50) NULL,
    "Range" varchar(50) NULL,
    Expression varchar(50) NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_ReceiptTemplate PRIMARY KEY (TempID)
);

-- =========================================================
-- Rent_DepRateOnCT
-- =========================================================

CREATE TABLE Rent_DepRateOnCT (
    DepID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ClientID integer NULL,
    MinYear integer NULL,
    MaxYear integer NULL,
    "CTID" integer NULL,
    Per double precision NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_Rent_DepRateOnCT PRIMARY KEY (DepID)
);

-- =========================================================
-- Rent_RepairingRateOnCT
-- =========================================================

CREATE TABLE Rent_RepairingRateOnCT (
    RepID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ClientID integer NULL,
    MinYear integer NULL,
    MaxYear integer NULL,
    "CTID" integer NULL,
    Per double precision NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_Rent_RepRateOnCT PRIMARY KEY (RepID)
);

-- =========================================================
-- Settings
-- =========================================================

CREATE TABLE Settings (
    SettingName varchar(50) NULL,
    StringValue varchar(50) NULL,
    IntegerValue integer NULL,
    FloatValue double precision NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- States
-- =========================================================

CREATE TABLE States (
    StateID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    StateName varchar(100) NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_States PRIMARY KEY (StateID)
);

-- =========================================================
-- TaxDemandPaymentDetails
-- =========================================================

CREATE TABLE TaxDemandPaymentDetails (
    DID bigint NULL,
    TaxID integer NULL,
    PreviousBalance integer DEFAULT 0 NULL,
    CurrentBalance integer DEFAULT 0 NULL,
    PreviousPaid integer DEFAULT 0 NULL,
    CurrentPaid integer DEFAULT 0 NULL,
    RemPreviousBalance integer DEFAULT 0 NULL,
    RemCurrentBalance integer DEFAULT 0 NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- TaxDemands
-- =========================================================

CREATE TABLE TaxDemands (
    DID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    RECNO bigint NOT NULL,
    ACID bigint NULL,
    DDate date NULL,
    FYID integer NULL,
    SumPrevious integer NULL,
    SumNew integer NULL,
    SumTotal integer NULL,
    ExAdjustment integer NULL,
    Advance integer NULL,
    Adjustment integer NULL,
    Discount integer NULL,
    TotalPayableAmt integer NULL,
    InWords varchar(100) NULL,
    DPAID smallint NULL,
    TranID bigint NULL,
    WaterTax double precision NULL,
    MainDemand boolean DEFAULT false NOT NULL,
    locked boolean DEFAULT false NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_TaxDemand PRIMARY KEY (DID)
);

-- =========================================================
-- TaxPaymentDetails
-- =========================================================

CREATE TABLE TaxPaymentDetails (
    PYID bigint NULL,
    DID bigint NULL,
    TaxID integer NULL,
    LedgerID bigint NULL,
    BalancePaid double precision NULL,
    CurrentPaid double precision NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- TaxPayments
-- =========================================================

CREATE TABLE TaxPayments (
    PYID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DID bigint NULL,
    RECNO bigint NULL,
    ACID bigint NULL,
    DDate timestamp NULL,
    FYID integer NULL,
    SumPrevious double precision NULL,
    SumCurrent double precision NULL,
    ExAdjustment double precision NULL,
    Advance double precision NULL,
    Discount double precision NULL,
    CashDiscount double precision NULL,
    BalanceAmt double precision NULL,
    ExcessAmt double precision NULL,
    WaterTax double precision NULL,
    TotalBillAmt double precision NULL,
    TotalPayableAmt double precision NULL,
    AmountPaid double precision NULL,
    InWords varchar(100) NULL,
    PaymentMode varchar(50) NULL,
    InstrumentNo varchar(50) NULL,
    InstrumentDate date NULL,
    BankName varchar(50) NULL,
    Receiver varchar(50) NULL,
    ReceivedFrom varchar(50) NULL,
    TRANID bigint NULL,
    Penalty double precision NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_TaxPayment PRIMARY KEY (PYID)
);

-- =========================================================
-- TaxRates
-- =========================================================

CREATE TABLE TaxRates (
    MinArea integer NULL,
    MaxArea integer NULL,
    Amount double precision NULL,
    Per double precision NULL,
    TSRate1 integer DEFAULT 0 NULL,
    TSRate2 integer DEFAULT 0 NULL,
    TaxID integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- TaxTypes
-- =========================================================

CREATE TABLE TaxTypes (
    TaxID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TaxType varchar(50) NULL,
    TaxOverToiletSeat boolean DEFAULT false NULL,
    TaxOnWaterConnection boolean NULL,
    TaxOnWholeProperty boolean NULL,
    EducationTax boolean NULL,
    EmploymentTax boolean NULL,
    UsageTax boolean DEFAULT false NULL,
    PropertyTax boolean DEFAULT false NULL,
    FireSafetyTax boolean DEFAULT false NULL,
    AdvtTax boolean DEFAULT false NULL,
    SpecialTax boolean DEFAULT false NULL,
    OrdNo integer NULL,
    fix boolean NULL,
    ValuedOn integer NULL,
    LedgerID integer NULL,
    OldTax boolean DEFAULT false NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_TaxTypes PRIMARY KEY (TaxID)
);

-- =========================================================
-- Taxprodeal
-- =========================================================

CREATE TABLE Taxprodeal (
    PDID integer NULL,
    TaxID integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- TowerTaxPer
-- =========================================================

CREATE TABLE TowerTaxPer (
    ID integer NULL,
    TowerPer integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- Transactions
-- =========================================================

CREATE TABLE Transactions (
    TranID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    FYID integer NULL,
    TranDate timestamp NULL,
    VoucherType smallint NULL,
    VoucherNo integer NULL,
    TranDetails varchar(100) NULL,
    Remarks varchar(100) NULL,
    Amount double precision NULL,
    UserID integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_Transactions PRIMARY KEY (TranID)
);

-- =========================================================
-- UsageLog
-- =========================================================

CREATE TABLE UsageLog (
    LogID bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    LogType varchar(50) NULL,
    Description text NULL,
    LogDate timestamp NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_UsageLog PRIMARY KEY (LogID)
);

-- =========================================================
-- Users
-- =========================================================

CREATE TABLE Users (
    UserID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    UserName varchar(50) NULL,
    Mobile varchar(50) NULL,
    DOB date NULL,
    EMail varchar(50) NULL,
    LoginID varchar(50) NULL,
    "Password" varchar(255) NULL,
    UserRole varchar(50) NULL,
    UserLocation boolean NULL,
    ClientID integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_Users PRIMARY KEY (UserID)
);

-- =========================================================
-- VMValue
-- =========================================================

CREATE TABLE VMValue (
    VMID integer NOT NULL,
    ValuedOn varchar(50) NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_VMValue PRIMARY KEY (VMID)
);

-- =========================================================
-- WaterConnections
-- =========================================================

CREATE TABLE WaterConnections (
    ACID bigint NULL,
    Owner_Name varchar(50) NULL,
    Pipe_Size varchar(50) NULL,
    size_value integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- Weightages
-- =========================================================

CREATE TABLE Weightages (
    ZID integer NULL,
    PTID integer NULL,
    Weightage double precision NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL
);

-- =========================================================
-- Zones
-- =========================================================

CREATE TABLE Zones (
    ZID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ZoneName varchar(100) NULL,
    PointsPer double precision DEFAULT 0.0 NULL,
    ClientID integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_Zones PRIMARY KEY (ZID)
);

-- =========================================================
-- AccountsPhotos
-- =========================================================

CREATE TABLE AccountsPhotos (
    ImageId integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ACID bigint NOT NULL,
    FileName varchar(255) NULL,
    MimeType varchar(50) NULL,
    ImagePath varchar(500) NOT NULL,
    CONSTRAINT PK__Accounts__7516F70C889A2488 PRIMARY KEY (ImageId),
    CONSTRAINT FK__AccountsPh__ACID__5B438874
        FOREIGN KEY (ACID)
        REFERENCES Accounts(ACID)
);

-- =========================================================
-- Talukas
-- =========================================================

CREATE TABLE Talukas (
    TalukaID integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TalukaName varchar(100) NULL,
    DistID integer NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT PK_Talukas PRIMARY KEY (TalukaID),
    CONSTRAINT FK_Talukas_Districts
        FOREIGN KEY (DistID)
        REFERENCES Districts(DistID)
);

-- =========================================================
-- TaxDemandDetails
-- =========================================================

CREATE TABLE TaxDemandDetails (
    DID bigint NULL,
    TaxID integer NULL,
    PreviousBalance double precision NULL,
    CurrentBalance double precision NULL,
    TotalBalance double precision NULL,
    LedgerID bigint NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT FK_TaxDemandDetails_TaxDemands
        FOREIGN KEY (DID)
        REFERENCES TaxDemands(DID)
        ON DELETE CASCADE
);

-- =========================================================
-- TransactionDetails
-- =========================================================

CREATE TABLE TransactionDetails (
    TranID bigint NULL,
    SN smallint NULL,
    LedgerID1 bigint NULL,
    LedgerID2 bigint NULL,
    Debit numeric(12,2) NULL,
    Credit numeric(12,2) NULL,
    DrCr char(2) NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    deleted_at timestamp NULL,
    sync_version bigint DEFAULT 1 NULL,
    CONSTRAINT FK_TransactionDetails_Transactions
        FOREIGN KEY (TranID)
        REFERENCES Transactions(TranID)
        ON DELETE CASCADE
);
